### ISSUE TITLE
Angular 2 Universal production ready

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#247]
- [ ] allow templateUrl or styleUrls to work https://github.com/angular/universal/issues/294
- [ ] allow better SystemJS support by tracking `System.import` https://github.com/angular/universal/issues/283
- [ ] create Universal localStorage module https://github.com/angular/universal/issues/272
- [ ] create Universal cookies module https://github.com/angular/universal/issues/273
- [ ] create Universal IndexDB module
- [ ] prototype NgCache https://github.com/angular/universal/issues/271
- [ ] write docs for all modules https://github.com/angular/universal/issues/258
- [ ] write docs for quick-start
- [ ] render single component https://github.com/angular/universal/issues/347
- [ ] allow creation of context to load the universal app https://github.com/angular/universal/issues/284  **_blocked_**
- [x] make preboot work with multiple apps https://github.com/angular/universal/issues/303  **!important**
- [x] isNode/isBrowser https://github.com/angular/universal/issues/397
- [x] Jsonp support https://github.com/angular/universal/issues/409
- [x] remove `-preview`
- [x] fix setTimeout on the server https://github.com/angular/universal/issues/267
- [x] allow `|async` AsyncPipe to work before rendering https://github.com/angular/universal/issues/327
- [x] allow `https` for `NodeConnection` https://github.com/angular/universal/issues/326
- [x] allow devs to control when to render without `zone.js` with lifecycle hook https://github.com/angular/universal/commit/06d3a51bff23d358ceccb1ee4d571793657f889c
- [x] allow async requests from `Http` to work
- [x] allow async requests from `Http` to work with precache https://github.com/angular/universal/issues/274 **!important**
- [x] allow dev to create an HTML component https://github.com/angular/angular/pull/7455
- [x] create polyfills module https://github.com/angular/universal/issues/193
- [x] rename `server` to `node`
- [x] remove `angular2-` prefix in `modules/` #295
- [x] allow replay of common events for preboot https://github.com/angular/universal/issues/245
- [x] example of 3rd Party Module with Universal support [angular2-universal-module](https://github.com/gdi2290/angular2-universal-module)
- [x] allow optional route params with pre-rendered views https://github.com/angular/universal/issues/275 https://github.com/angular/angular/pull/7431
- [x] mock out window object on global for warnings https://github.com/angular/universal/pull/311
- [x] create universal-preview module to warn developers https://github.com/angular/universal/pull/315
- [x] include more attributes from properties

bonus:
- [ ] create Universal localForage module
- [x] make prerendering work with multiple apps https://github.com/angular/universal/issues/259
- [x] isolate modules from shared build/typings
- [x] switch to typings from tsd https://github.com/angular/universal/issues/206
- [x] use Http for NodeConnection https://github.com/angular/universal/issues/264

**Comment by robwormald** [comment]
worth considering starting to use npm scoped packages here:
`@angular2/universal`

**Comment by gdi2290** [comment]
yup that would be legit

**Comment by NiklasRaab** [comment]
Whats about SystemJs support?

**Comment by wizardnet972** [comment]
@gdi2290 @robwormald 
Yeah? how? I'm getting an error message on the build to production:

I'm running npm `build:aot`
Then: `cd dist`
run: `node server.js`
go to: http://localhost:8000

I get error message:
Error: Failed to lookup view "../dist/index" in views directory "src"

Try for yourself!

**Comment by Koslun** [comment]
@wizardnet972 if the starter doesn't work straight out-of-the-box you should rather put that issue on the repository for that starter.

If you have some other custom configuration it might be better to turn it over to stackoverflow.

Regardless the main universal logic is now merged into the [angular core repository](https://github.com/angular/angular) and this repository only contains the old logic for angular 2.X and some wrapper modules to more easily use what's in the core of angular.

**Comment by MarkPieszak** [comment]
@wizardnet972 which starter are you using? The angular/universal-starter has been updated can you try that one and see if everything works for you?
