### ISSUE TITLE
tracking: features

### ISSUE THREAD

**Issue by Toxicable** [angular/universal#794]
**Easy**
- [ ] Better internal performance and stress tests
- In progress
- [ ] Make it easier to write unit tests for Universal components
- related https://github.com/angular/universal/issues/800
- [x] Support AppShell use cases
- related https://github.com/angular/angular-cli/pull/7780
- [x] Hooks in renderModule* to do stuff just before rendering to string
- done via https://github.com/angular/angular/commit/8dfc3c386af17977547500b9fb3b7974991a770a
- [x] Generic state transfer API in the platform
- done via https://github.com/angular/angular/commit/cfd9ca0d6f453decc154cc640351f5af67685510
- [x] Http Transfer State Module that uses HTTP interceptors and state transfer API
- done via https://github.com/angular/universal/commit/23a89ecc05b36b3b393e68b7ea51335b9690dfd6
- [x] Unified Document Service that combines Meta and Title services and adds more features
- No longer needed as per https://github.com/angular/angular/commit/2f2d5f35bd086abeafceabdd5ff9430221b1917f but maybe some docs around this?
- [x] Angular CLI support for Universal
- Done via https://github.com/angular/angular-cli/wiki/stories-universal-rendering
- [x] Material 2 works on Universal
- The majority of components are done
- See here for list: https://github.com/angular/material2/blob/master/src/universal-app/kitchen-sink/kitchen-sink.ts
- Tracking https://github.com/angular/material2/issues/308

**Not Easy**
- [ ] Full client rehydration strategy that reuses DOM elements/CSS rendered on the server
- [ ] Make it easier to support other 3rd part libraries like jQuery/d3 that aren't Universal aware
- [ ] Node.js bridge protocol to communicate with different language backends - Django, Go, PHP etc.

**Comment by gdi2290** [comment]
* the rehydration strategy involves some changes with angular core or a lot more code to workaround some problems.
* the latest version of angular uses [domino](https://github.com/fgnass/domino) which offers for operators. you can simply inject DOCUMENT

**Comment by Toxicable** [comment]
@gdi2290 
>the latest version of angular uses domino which offers for operators. you can simply inject DOCUMENT

That's what I indicating towards with:
> No longer needed as per angular/angular@2f2d5f3 but maybe some docs around this?

**Comment by Toxicable** [comment]
Since most here is done will track individually
